const test = require('node:test');
const assert = require('node:assert/strict');
const { isGoogleMapsLink } = require('../js/maps-utils');

test('accepts standard Google Maps URLs', () => {
  assert.equal(isGoogleMapsLink('https://www.google.com/maps/place/Cairo'), true);
  assert.equal(isGoogleMapsLink('https://maps.google.com/?q=Cairo'), true);
});

test('accepts share links generated by Google Maps', () => {
  assert.equal(isGoogleMapsLink('https://maps.app.goo.gl/AbCdEf123'), true);
  assert.equal(isGoogleMapsLink('https://goo.gl/maps/AbCdEf123'), true);
});

test('rejects non-Google and malformed URLs', () => {
  assert.equal(isGoogleMapsLink('https://example.com/maps'), false);
  assert.equal(isGoogleMapsLink('not-a-url'), false);
  assert.equal(isGoogleMapsLink('javascript:alert(1)'), false);
});
