"use client";
import {FormEvent,useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
export default function AuthPage(){
 const [mode,setMode]=useState<"login"|"signup">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[user,setUser]=useState<string|null>(null);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user?.email??null))},[]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");if(mode==="signup"){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{name:name.trim()},emailRedirectTo:window.location.origin+"/auth"}});if(error)setMessage(error.message);else if(data.session)window.location.href="/account";else setMessage("الحساب اتعمل. راجع بريدك لتأكيد الإيميل.");}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message);else window.location.href="/account"}setLoading(false)}
 async function logout(){await supabase.auth.signOut();setUser(null)}
 if(user)return <main className="account-page" dir="rtl"><div className="auth-panel"><div className="auth-visual"><span>ELGEWALIY / ACCOUNT</span><strong>رجعت تاني.</strong><p>حسابك بيجمع طلباتك في مكان واحد.</p></div><div className="auth-form"><a href="/" className="auth-brand"><span className="brand-mark">ج</span><span><strong>الجويلي</strong><small>ELGEWALIY FASHION CENTER</small></span></a><span className="flow-label">ACCOUNT / 01</span><h1>أهلاً بيك</h1><p>{user}</p><div className="auth-actions"><a href="/account" className="form-next">فتح حسابي →</a><button onClick={logout} className="form-back">تسجيل الخروج</button><a href="/" className="auth-text-link">العودة للمتجر</a></div></div></div></main>;
 return <main className="account-page" dir="rtl"><div className="auth-panel"><div className="auth-visual"><span>ELGEWALIY / ACCOUNT</span><strong>{mode==="login"?"كل طلبك قريب.":"خطوة وتبقى معانا."}</strong><p>{mode==="login"?"ادخل عشان تشوف طلباتك وتتابعها.":"اعمل حساب عشان تحفظ بياناتك وتتابع طلباتك بسهولة."}</p><div className="auth-stats"><span>01 / الحساب</span><span>02 / الطلبات</span><span>03 / التتبع</span></div></div><div className="auth-form"><a href="/" className="auth-brand"><span className="brand-mark">ج</span><span><strong>الجويلي</strong><small>ELGEWALIY FASHION CENTER</small></span></a><span className="flow-label">{mode==="login"?"WELCOME BACK / 01":"JOIN ELGEWALIY / 01"}</span><h1>{mode==="login"?"سجل دخولك":"اعمل حساب جديد"}</h1><p>{mode==="login"?"بيانات بسيطة وتدخل على طلباتك.":"استخدم بريدك الإلكتروني وكلمة مرور لحسابك."}</p><form className="auth-fields" onSubmit={submit}>{mode==="signup"&&<label><span>الاسم</span><input value={name} onChange={e=>setName(e.target.value)} required autoComplete="name" placeholder="الاسم بالكامل"/></label>}<label><span>البريد الإلكتروني</span><input value={email} onChange={e=>setEmail(e.target.value)} required type="email" autoComplete="email" placeholder="name@example.com"/></label><label><span>كلمة المرور</span><input value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} type="password" autoComplete={mode==="login"?"current-password":"new-password"} placeholder="••••••••"/></label>{message&&<div className="form-error" role="alert">{message}</div>}<button className="auth-submit" disabled={loading}>{loading?"جارٍ التنفيذ...":mode==="login"?"تسجيل الدخول":"إنشاء الحساب"} <span>→</span></button></form><div className="auth-switch">{mode==="login"?"لسه معندكش حساب؟":"عندك حساب بالفعل؟"} <button onClick={()=>{setMode(mode==="login"?"signup":"login");setMessage("")}}>{mode==="login"?"اعمل حساب":"سجل دخول"}</button></div><a href="/" className="auth-text-link">← العودة للمتجر</a></div></div></main>
}