"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

export default function AuthPage(){
 const [mode,setMode]=useState<"login"|"signup">("login");
 const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState("");
 const [loading,setLoading]=useState(false); const [message,setMessage]=useState(""); const [user,setUser]=useState<string|null>(null);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user?.email??null))},[]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage("");
  if(mode==="signup"){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{name},emailRedirectTo:window.location.origin+"/auth"}});if(error)setMessage(error.message);else if(data.session){window.location.href="/account"}else setMessage("الحساب اتعمل. راجع بريدك لتأكيد الإيميل ثم ارجع هنا.");}
  else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message);else window.location.href="/account";}setLoading(false);
 }
 async function logout(){await supabase.auth.signOut();setUser(null)}
 if(user)return <main className="auth-shell"><div className="auth-card text-center"><span className="brand-mark">ج</span><span className="section-kicker">ACCOUNT</span><h1 className="mt-2 text-3xl font-black">أهلاً بيك في الجويلي</h1><p className="mt-3 text-zinc-500">{user}</p><div className="mt-7 grid gap-3"><a href="/account" className="rounded-2xl bg-orange-500 py-4 font-black text-white">فتح حسابي</a><button onClick={logout} className="rounded-2xl border border-zinc-200 py-4 font-black">تسجيل الخروج</button><a href="/" className="py-2 text-sm font-bold text-orange-600">العودة للمتجر</a></div></div></main>;
 return <main className="auth-shell"><div className="auth-card"><a href="/" className="brand-lockup"><span className="brand-mark">ج</span><span><b className="block text-xl">الجويلي</b><small>ELGEWALIY</small></span></a><div className="mt-10"><span className="section-kicker">{mode==="login"?"WELCOME BACK":"JOIN ELGEWALIY"}</span><h1 className="mt-2 text-3xl font-black">{mode==="login"?"سجل دخولك":"اعمل حساب جديد"}</h1><p className="mt-3 text-sm leading-6 text-zinc-500">{mode==="login"?"ادخل عشان تتابع طلباتك وتحفظ تجربة الشراء.":"حسابك يخليك تتابع الطلبات وترجع لمعلوماتك بسهولة."}</p></div><form onSubmit={submit} className="mt-7 grid gap-4">{mode==="signup"&&<input required value={name} onChange={e=>setName(e.target.value)} placeholder="الاسم" className="auth-input"/>}<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="البريد الإلكتروني" className="auth-input"/><input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="كلمة المرور" className="auth-input"/>{message&&<div className="rounded-2xl bg-orange-50 p-4 text-sm leading-6 text-orange-800">{message}</div>}<button disabled={loading} className="rounded-2xl bg-zinc-950 py-4 font-black text-white shadow-lg transition hover:bg-orange-500 disabled:opacity-50">{loading?"جارٍ التنفيذ...":mode==="login"?"تسجيل الدخول":"إنشاء الحساب"}</button></form><div className="mt-6 text-center text-sm text-zinc-500">{mode==="login"?"لسه معندكش حساب؟":"عندك حساب بالفعل؟"} <button onClick={()=>{setMode(mode==="login"?"signup":"login");setMessage("")}} className="font-black text-orange-600">{mode==="login"?"اعمل حساب":"سجل دخول"}</button></div><a href="/" className="mt-5 block text-center text-xs font-bold text-zinc-400">← العودة للمتجر</a></div></main>
}
