"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Order={id:string;order_number:string;total:number;status:string;created_at:string};

const statusLabel:Record<string,string>={new:"تم استلام الطلب",preparing:"جاري التجهيز",shipped:"خرج للتوصيل",delivered:"تم التسليم",cancelled:"تم إلغاء الطلب"};

export default function Account(){
 const [email,setEmail]=useState(""); const [orders,setOrders]=useState<Order[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/auth";return}setEmail(user.email??"");const {data:customer}=await supabase.from("customers").select("id").eq("auth_user_id",user.id).maybeSingle();if(customer){const {data}=await supabase.from("orders").select("id,order_number,total,status,created_at").eq("customer_id",customer.id).order("created_at",{ascending:false});if(data)setOrders(data as Order[])}setLoading(false)})()},[]);
 async function logout(){await supabase.auth.signOut();window.location.href="/"}
 return <main className="min-h-screen bg-[#fffaf5] p-4"><div className="mx-auto max-w-4xl py-8 md:py-14"><div className="flex items-center justify-between"><a href="/" className="brand-lockup"><span className="brand-mark">ج</span><span><b className="block text-xl">الجويلي</b><small>ELGEWALIY</small></span></a><button onClick={logout} className="rounded-full border border-zinc-200 bg-white px-4 py-2 text-sm font-black">تسجيل الخروج</button></div><section className="mt-8 rounded-[30px] bg-zinc-950 p-7 text-white shadow-2xl md:p-10"><span className="section-kicker text-orange-400">MY ACCOUNT</span><h1 className="mt-2 text-3xl font-black">حسابي</h1><p className="mt-3 text-white/60">{email}</p></section><section className="mt-6 rounded-[30px] bg-white p-6 shadow-sm md:p-8"><div className="flex items-end justify-between"><div><span className="section-kicker">ORDERS</span><h2 className="mt-1 text-2xl font-black">طلباتي</h2></div><a href="/track" className="text-sm font-black text-orange-600">تتبع طلب ↗</a></div>{loading?<p className="py-12 text-center text-zinc-500">جارٍ تحميل الطلبات...</p>:orders.length===0?<div className="py-12 text-center"><p className="text-zinc-500">لسه مفيش طلبات على الحساب.</p><a href="/" className="mt-4 inline-block rounded-xl bg-orange-500 px-5 py-3 text-sm font-black text-white">ابدأ التسوق</a></div>:<div className="mt-6 space-y-3">{orders.map(order=><a href={"/track?order="+order.order_number} key={order.id} className="block rounded-2xl border border-zinc-100 p-4 transition hover:-translate-y-0.5 hover:border-orange-200 hover:shadow-lg"><div className="flex items-center justify-between gap-3"><div><b>{order.order_number}</b><p className="mt-1 text-xs text-zinc-500">{new Date(order.created_at).toLocaleDateString("ar-EG")}</p></div><div className="text-left"><b className="text-orange-600">{order.total} ج.م</b><p className="mt-1 text-xs font-bold text-zinc-500">{statusLabel[order.status]??order.status}</p></div></div></a>)}</div>}</section></div></main>
}
