"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
type Order={id:string;order_number:string;total:number;status:string;created_at:string};
const statusLabel:Record<string,string>={new:"تم استلام الطلب",accepted:"تم قبول الطلب",preparing:"جاري التجهيز",ready:"الطلب جاهز",shipped:"خرج للتوصيل",out_for_delivery:"خرج للتوصيل",delivered:"تم التسليم",cancelled:"تم إلغاء الطلب"};
export default function Account(){
 const [email,setEmail]=useState(""),[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/auth";return}setEmail(user.email??"");const {data:customer}=await supabase.from("customers").select("id").eq("auth_user_id",user.id).maybeSingle();if(customer?.id){const {data}=await supabase.from("orders").select("id,order_number,total,status,created_at").eq("customer_id",customer.id).order("created_at",{ascending:false});if(data)setOrders(data as Order[])}setLoading(false)})()},[]);
 async function logout(){await supabase.auth.signOut();window.location.href="/"}
 return <main className="dashboard-page" dir="rtl"><div className="dashboard-shell"><header className="dashboard-header"><a href="/" className="auth-brand"><span className="brand-mark">ج</span><span><strong>الجويلي</strong><small>ELGEWALIY FASHION CENTER</small></span></a><div><a href="/" className="dashboard-link">المتجر</a><button onClick={logout} className="dashboard-logout">تسجيل الخروج</button></div></header><section className="account-hero"><div><span className="flow-label light">MY ACCOUNT / 04</span><h1>حسابي.</h1><p>{email}</p></div><a href="/track" className="account-hero-action">تتبع طلب <span>←</span></a></section><section className="orders-section"><div className="section-head"><div><span className="flow-label">ORDERS / 01</span><h2>طلباتي</h2><p>كل الطلبات المؤكدة المرتبطة بحسابك.</p></div><a href="/" className="account-continue">كمل التسوق →</a></div>{loading?<div className="orders-empty">جارٍ تحميل الطلبات...</div>:orders.length===0?<div className="orders-empty"><strong>لسه مفيش طلبات.</strong><p>لما تعمل أول طلب هتلاقيه هنا ومعاه حالة التتبع.</p><a href="/">ابدأ التسوق</a></div>:<div className="orders-list">{orders.map(o=><a className="order-row" href={"/track?order="+encodeURIComponent(o.order_number)} key={o.id}><div><span>{o.order_number}</span><small>{new Date(o.created_at).toLocaleDateString("ar-EG")}</small></div><div><strong>{o.total} ج.م</strong><small>{statusLabel[o.status]||o.status}</small></div><b>←</b></a>)}</div>}</section></div></main>
}