"use client";
import {useEffect,useMemo,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {supabase} from "@/lib/supabase";
import {addCartItem,type CartItem} from "@/lib/cart";
import {selectVariant,uniqueOptions,type VariantLike} from "@/lib/product-variants";
import type {Product} from "@/lib/types";
type Variant=VariantLike&{product_id:string};type Image={id:string;url:string;alt_ar:string|null;alt_en:string|null;sort_order:number};
const money=(n:number)=>new Intl.NumberFormat("ar-EG",{maximumFractionDigits:0}).format(n)+" ج.م";
export default function ProductPage(){
 const params=useParams<{slug:string}>(),router=useRouter();const [product,setProduct]=useState<Product|null>(null),[variants,setVariants]=useState<Variant[]>([]),[images,setImages]=useState<Image[]>([]),[size,setSize]=useState<string|null>(null),[color,setColor]=useState<string|null>(null),[qty,setQty]=useState(1),[error,setError]=useState(""),[active,setActive]=useState(0);
 useEffect(()=>{(async()=>{const {data:p}=await supabase.from("products").select("*").eq("slug",params.slug).eq("is_active",true).maybeSingle();if(!p)return;setProduct(p as Product);const [{data:v},{data:i}]=await Promise.all([supabase.from("product_variants").select("id,product_id,size,color,stock,price_override").eq("product_id",p.id).eq("is_active",true),supabase.from("product_images").select("id,url,alt_ar,alt_en,sort_order").eq("product_id",p.id).order("sort_order")]);const list=(v||[]) as Variant[];setVariants(list);const o=uniqueOptions(list);setSize(o.sizes[0]??null);setColor(o.colors[0]??null);setImages((i||[]) as Image[])})()},[params.slug]);
 const options=useMemo(()=>uniqueOptions(variants),[variants]),variant=useMemo(()=>selectVariant(variants,size,color),[variants,size,color]),price=Number(variant?.price_override??product?.price??0),image=images[active]?.url||images[0]?.url||null;
 function add(){if(!product)return;if(variants.length&&!variant){setError("اختار المقاس واللون المتاحين.");return}if(variant&&variant.stock<qty){setError("الكمية المطلوبة مش متاحة.");return}const item:CartItem={key:product.id+"-"+(variant?.id??"base"),productId:product.id,variantId:variant?.id,name_ar:product.name_ar,name_en:product.name_en,price,compare_at_price:product.compare_at_price,size:variant?.size??size,color:variant?.color??color,quantity:qty};try{const raw=JSON.parse(localStorage.getItem("elgewaliy-cart")||"[]");localStorage.setItem("elgewaliy-cart",JSON.stringify(addCartItem(Array.isArray(raw)?raw:[],item)));router.push("/?cart=open")}catch{setError("تعذر إضافة المنتج للسلة.")}}
 if(!product)return <main className="product-page"><div className="product-loading">جارٍ تحميل المنتج...</div></main>;
 return <main className="product-page" dir="rtl"><header className="product-header"><a href="/" className="auth-brand"><span className="brand-mark">ج</span><span><strong>الجويلي</strong><small>ELGEWALIY FASHION CENTER</small></span></a><nav><a href="/#catalog">التشكيلة</a><a href="/track">تتبع الطلب</a><a href="/auth">حسابي</a></nav></header><section className="product-detail"><div className="product-gallery"><div className="gallery-main">{image?<img src={image} alt={images[active]?.alt_ar||product.name_ar}/>:<div className="placeholder"><strong>الجويلي</strong></div>}<span className="gallery-index">{String(active+1).padStart(2,"0")} / {String(Math.max(images.length,1)).padStart(2,"0")}</span></div>{images.length>1&&<div className="gallery-thumbs">{images.map((i,n)=><button key={i.id} className={active===n?"active":""} onClick={()=>setActive(n)}><img src={i.url} alt=""/></button>)}</div>}</div><div className="product-info"><span className="flow-label">PRODUCT / DETAIL</span><h1>{product.name_ar}</h1><p className="product-en">{product.name_en}</p><div className="product-price">{money(price)} {product.compare_at_price?<del>{money(Number(product.compare_at_price))}</del>:null}</div><p className="product-desc">{product.description_ar||"قطعة مختارة من تشكيلة الجويلي."}</p>{options.sizes.length>0&&<div className="selection"><div><strong>المقاس</strong><span>{size||"اختار"}</span></div><div className="selection-row">{options.sizes.map(s=>{const ok=variants.some(v=>v.size===s&&(color==null||v.color===color)&&v.stock>0);return <button key={s} disabled={!ok} className={size===s?"selected":""} onClick={()=>ok&&(setSize(s),setError(""))}>{s}</button>})}</div></div>}{options.colors.length>0&&<div className="selection"><div><strong>اللون</strong><span>{color||"اختار"}</span></div><div className="selection-row">{options.colors.map(c=>{const ok=variants.some(v=>v.color===c&&(size==null||v.size===size)&&v.stock>0);return <button key={c} disabled={!ok} className={color===c?"selected":""} onClick={()=>ok&&(setColor(c),setError(""))}>{c}</button>})}</div></div>}<div className="product-qty"><button onClick={()=>setQty(v=>Math.max(1,v-1))}>−</button><strong>{qty}</strong><button disabled={!!variant&&qty>=variant.stock} onClick={()=>setQty(v=>v+1)}>+</button><span>{variant?"المتاح: "+variant.stock:""}</span></div>{error&&<div className="form-error">{error}</div>}<button className="product-add" disabled={variants.length>0&&!variant} onClick={add}>أضف للسلة <span>←</span></button><a className="product-back" href="/">← العودة للتشكيلة</a></div></section></main>
}